version: '3'

services:
  api:
    build: ./api
    container_name: phishing_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  
      - ./datasets:/app/datasets  

  app:
    build: ./app
    container_name: phishing_app
    ports:
      - "8501:8501"
    depends_on:
      - api
